---

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400
  when: ansible_os_family == 'Debian'

- name: Gather | os info
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yaml"
  tags: vars

- name: Cowrie storage
  file:
    path: "{{ cowrie_storage_path }}"
    state: directory


- name: Install system level packages
  package:
    name: "{{ item }}"
  with_items: "{{ global_packages + os_packages }}"

- name: Install python modules
  pip:
    name: docker

- name: Enable docker
  service:
    name: docker
    enabled: true
    state: started

- name: Include CHN Container and deps
  include_role:
    name: chn-server
  when: bundle_chn

# Oof this is ugly
- name: Extract Deploy key
  shell: docker exec chnserver awk '/DEPLOY_KEY/' /opt/config.py | awk -F ' = ' '{print $2}' | sed -e "s/'//g"
  register: chn_deploy_key_extract
  changed_when: false
  when: bundle_chn

- name: Set deploy key - Bundled
  set_fact:
    chn_deploy_key: "{{ chn_deploy_key_extract.stdout }}"
  when: bundle_chn

- name: Cowrie sysconfig
  template:
    src: cowrie.sysconfig.j2
    dest: "{{ cowrie_storage_path }}/cowrie.sysconfig"

- name: Pull in cowrie images
  docker_image:
    name: "{{ item }}"
    timeout: 300
  with_items:
    - "stingar/cowrie:{{ chn_version_tag }}"
  when: not cowrie_build_images

- name: Build Images
  include_tasks: build_images.yaml
  when: cowrie_build_images

- name: Set fact for bundled links
  set_fact:
    cowrie_container_links:
      - "chn-server:chnserver"
      - "hpfeeds:hpfeeds"
  when: bundle_chn

- name: Set fact for non-bundled links
  set_fact:
    cowrie_container_links: []
  when: not bundle_chn

- name: Standalone Deploy Cowrie container
  docker_container:
    name: cowrie
    image: stingar/cowrie:latest
    state: started
    log_driver: journald
    restart_policy: always
    links: "{{ cowrie_container_links }}"
    volumes:
      - "{{ cowrie_storage_path }}/cowrie.sysconfig:{{ cowrie_env_file }}"
      - "{{ cowrie_storage_path }}/cowrie:/etc/cowrie"
    ports:
      - '22:2222'
  tags:
    - docker
