---
dependency:
  name: gilt
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  options:
    config-file: './.yamllint'
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        bundle_chn: true
    host_vars:
      cowrie-ubuntu18-builder:
        ansible_python_interpreter: "/usr/bin/python3"
        cowrie_build_images: true
      cowrie-ubuntu16-builder:
        ansible_python_interpreter: "/usr/bin/python3"
        cowrie_build_images: true
  lint:
    name: ansible-lint
    options:
      exclude:
        - molecule/roles/
verifier:
  name: testinfra
  lint:
    name: flake8

platforms:
  - name: cowrie-ubuntu18-builder
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    config_options:
      synced_folder: True
    box: ubuntu/bionic64
    memory: 1024
  - name: cowrie-ubuntu16-builder
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    config_options:
      synced_folder: True
    box: ubuntu/xenial64
    memory: 1024
scenario:
  name: builder
